[build]
  publish = "."
  functions = "netlify/functions"

# Redirigir peticiones de /api/posts a la función serverless de Netlify
[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/posts"
  status = 200

[[redirects]]
  from = "/api/posts/*"
  to = "/.netlify/functions/posts"
  status = 200

[[redirects]]
  from = "/api/courses"
  to = "/.netlify/functions/courses"
  status = 200

[[redirects]]
  from = "/api/courses/*"
  to = "/.netlify/functions/courses"
  status = 200

# Excepciones para archivos estáticos dentro de la subruta /curso/
[[redirects]]
  from = "/curso/animaciones/*"
  to = "/animaciones/:splat"
  status = 200

[[redirects]]
  from = "/curso/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/curso/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/curso/:courseId"
  to = "/curso.html?courseId=:courseId"
  status = 200

# Cabeceras de Seguridad HTTP Globales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"



